name-template: 'Release ${{ GITHUB_REF }}'
tag-template: '$AUTOINCREMENT'
change-template: '- ${{ CHANGE_TITLE }}'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
template: |
  ## What's Changed
  $CHANGES
