name: Enforce PR Source

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-pr-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Source
        run: |
          if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Pull requests to main branch can only come from develop branch."
            exit 1
          fi
