name: Release notes

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

  workflow_dispatch: # Manual trigger option

jobs:
  generate-release-notes:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read package.json version
        id: read_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: generate_release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Generated Release Notes
        id: read_release_notes
        run: |
          RELEASE_NOTES=$(cat .github/release-drafter/release-notes.md)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Publish Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
        run: |
          curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"tag_name\":\"${PACKAGE_VERSION}\",\"name\":\"Release ${PACKAGE_VERSION}\",\"body\":\"${RELEASE_NOTES}\",\"draft\":false,\"prerelease\":false}" \
          https://api.github.com/repos/${{ github.repository }}/releases
