name: Validate PR Source Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Source Branch
        run: |
          if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Pull requests to the main branch must come from the develop branch."
            exit 1
          fi

          if [ "${{ github.head_ref }}" == "main" ]; then
            echo "Pull requests from the main branch are not allowed."
            exit 1
          fi
